### ISSUE TITLE
Port to 1.12.2.

### ISSUE THREAD

**Issue by SfortzaPhantom** [nekomeowww/CustomDrones#6]
Heyyah! This mod seems to be abandoned a lot, so I'd ask if you are planning to port this to 1.12.2.

**Comment by nekomeowww** [comment]
I am sorry to tell you, nope. I have failed to refract the code in the very far past. I could transfer this repository to you for maintenance if you like.

**Comment by SfortzaPhantom** [comment]
Sure, I had some plans with studying Java, so I guess I can try to work with the port.

Not a simple task for me, but I'll try my best.

**Comment by nekomeowww** [comment]
Good luck on your Java journey then! You can ask me to transfer this repository whenever you ready to take over it.
